// GPC modules for LUT6 
// This file is generated by CTAGenerator 

// GPC(0,0,6;3) compression ratio : 2
module gpc006(in, out);

input [5:0] in;
output [2:0] out;

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h6996966996696996)) LUT6_0_ (.O(out[0]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h8117177e177e7ee8)) LUT6_1_ (.O(out[1]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'hfee8e880e8808000)) LUT6_2_ (.O(out[2]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

endmodule

// GPC(0,1,5;3) compression ratio : 2
module gpc015(in, out);

input [5:0] in;
output [2:0] out;

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h9669699696696996)) LUT6_0_ (.O(out[0]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'he8818117177e7ee8)) LUT6_1_ (.O(out[1]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'hfffefee8e8808000)) LUT6_2_ (.O(out[2]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

endmodule

// GPC(0,0,5;3) compression ratio : 1.66667
module gpc005(in, out);

input [4:0] in;
output [2:0] out;

gpc006 gpc006_inst(.in({1'b0,in[4],in[3],in[2],in[1],in[0]}), .out(out));
endmodule

// GPC(0,1,4;3) compression ratio : 1.66667
module gpc014(in, out);

input [4:0] in;
output [2:0] out;

gpc015 gpc015_inst(.in({in[4],1'b0,in[3],in[2],in[1],in[0]}), .out(out));
endmodule

// GPC(0,2,3;3) compression ratio : 1.66667
module gpc023(in, out);

input [4:0] in;
output [2:0] out;

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h9696969696969696)) LUT6_0_ (.O(out[0]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(1'b0));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'he81717e8e81717e8)) LUT6_1_ (.O(out[1]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(1'b0));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'hffe8e800ffe8e800)) LUT6_2_ (.O(out[2]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(1'b0));

endmodule

// GPC(0,2,4;4) compression ratio : 1.5
module gpc024(in, out);

input [5:0] in;
output [3:0] out;

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h6996699669966996)) LUT6_0_ (.O(out[0]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h7ee8811781177ee8)) LUT6_1_ (.O(out[1]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h7ffffee8fee88000)) LUT6_2_ (.O(out[2]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h8000000000000000)) LUT6_3_ (.O(out[3]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

endmodule

// GPC(1,1,4;4) compression ratio : 1.5
module gpc114(in, out);

input [5:0] in;
output [3:0] out;

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h6996699669966996)) LUT6_0_ (.O(out[0]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h81177ee881177ee8)) LUT6_1_ (.O(out[1]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h1177ffffee88000)) LUT6_2_ (.O(out[2]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'hfee8800000000000)) LUT6_3_ (.O(out[3]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

endmodule

// GPC(0,3,3;4) compression ratio : 1.5
module gpc033(in, out);

input [5:0] in;
output [3:0] out;

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h9696969696969696)) LUT6_0_ (.O(out[0]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h17e8e817e81717e8)) LUT6_1_ (.O(out[1]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h17ffffe8ffe8e800)) LUT6_2_ (.O(out[2]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'he800000000000000)) LUT6_3_ (.O(out[3]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

endmodule

// GPC(1,2,3;4) compression ratio : 1.5
module gpc123(in, out);

input [5:0] in;
output [3:0] out;

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h9696969696969696)) LUT6_0_ (.O(out[0]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'he81717e8e81717e8)) LUT6_1_ (.O(out[1]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h1717ffffe8e800)) LUT6_2_ (.O(out[2]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'hffe8e80000000000)) LUT6_3_ (.O(out[3]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

endmodule

// GPC(2,1,3;4) compression ratio : 1.5
module gpc213(in, out);

input [5:0] in;
output [3:0] out;

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h9696969696969696)) LUT6_0_ (.O(out[0]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h17e817e817e817e8)) LUT6_1_ (.O(out[1]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'he80017ff17ffe800)) LUT6_2_ (.O(out[2]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'hffffe800e8000000)) LUT6_3_ (.O(out[3]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

endmodule

// GPC(0,4,2;4) compression ratio : 1.5
module gpc042(in, out);

input [5:0] in;
output [3:0] out;

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h6666666666666666)) LUT6_0_ (.O(out[0]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h8778788778878778)) LUT6_1_ (.O(out[1]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h77f7ff87ff8f880)) LUT6_2_ (.O(out[2]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'hf880800080000000)) LUT6_3_ (.O(out[3]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

endmodule

// GPC(1,3,2;4) compression ratio : 1.5
module gpc132(in, out);

input [5:0] in;
output [3:0] out;

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h6666666666666666)) LUT6_0_ (.O(out[0]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h7887877878878778)) LUT6_1_ (.O(out[1]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h8007077f7ff8f880)) LUT6_2_ (.O(out[2]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'hfff8f88080000000)) LUT6_3_ (.O(out[3]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

endmodule

// GPC(2,2,2;4) compression ratio : 1.5
module gpc222(in, out);

input [5:0] in;
output [3:0] out;

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h6666666666666666)) LUT6_0_ (.O(out[0]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'h8778877887788778)) LUT6_1_ (.O(out[1]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'hf880077f077ff880)) LUT6_2_ (.O(out[2]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

(* RLOC = "X0Y0" *)
LUT6 #(.INIT(64'hfffff880f8800000)) LUT6_3_ (.O(out[3]),  .I0(in[0]), .I1(in[1]), .I2(in[2]), .I3(in[3]), .I4(in[4]), .I5(in[5]));

endmodule

// GPC(0,0,4;3) compression ratio : 1.33333
module gpc004(in, out);

input [3:0] in;
output [2:0] out;

gpc006 gpc006_inst(.in({1'b0,1'b0,in[3],in[2],in[1],in[0]}), .out(out));
endmodule

// GPC(0,1,3;3) compression ratio : 1.33333
module gpc013(in, out);

input [3:0] in;
output [2:0] out;

gpc015 gpc015_inst(.in({in[3],1'b0,1'b0,in[2],in[1],in[0]}), .out(out));
endmodule

// GPC(0,2,2;3) compression ratio : 1.33333
module gpc022(in, out);

input [3:0] in;
output [2:0] out;

gpc023 gpc023_inst(.in({in[3],in[2],1'b0,in[1],in[0]}), .out(out));
endmodule

// GPC(1,1,3;4) compression ratio : 1.25
module gpc113(in, out);

input [4:0] in;
output [3:0] out;

gpc114 gpc114_inst(.in({in[4],in[3],1'b0,in[2],in[1],in[0]}), .out(out));
endmodule

// GPC(0,3,2;4) compression ratio : 1.25
module gpc032(in, out);

input [4:0] in;
output [3:0] out;

gpc033 gpc033_inst(.in({in[4],in[3],in[2],1'b0,in[1],in[0]}), .out(out));
endmodule

// GPC(1,2,2;4) compression ratio : 1.25
module gpc122(in, out);

input [4:0] in;
output [3:0] out;

gpc123 gpc123_inst(.in({in[4],in[3],in[2],1'b0,in[1],in[0]}), .out(out));
endmodule

// GPC(2,1,2;4) compression ratio : 1.25
module gpc212(in, out);

input [4:0] in;
output [3:0] out;

gpc213 gpc213_inst(.in({in[4],in[3],in[2],1'b0,in[1],in[0]}), .out(out));
endmodule

